[package]
name = "doing-some-curves"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.2"
ark-secp256k1 = "0.4.0"
ark-serialize = { version = "0.4.2", features = ["derive"] }
ark-std = "0.4.0"
generic-array = "0.14.7"
hex = "0.4.3"
rand = "0.8.5"
sec1 = "0.7.3"
sha2 = "0.10.8"
